# latent_factor_model: MF
# loss_type: CE
source_embedding_size: 64
target_embedding_size: 64
# reg_weight: 1e-2
# mapping_function: non_linear
# mlp_hidden_size: [128]
# train_epochs: ["SOURCE:300","TARGET:300","OVERLAP:300"]
# train_epochs: ["SOURCE:30","TARGET:30","OVERLAP:30"]
train_epochs: ["TARGET:300"]
# train_epochs: ["SOURCE:0","TARGET:0","OVERLAP:10"]
# overlap_batch_size: 100



learning_rate: 0.001
mapping_function: non_linear
mlp_hidden_size: [64]
overlap_batch_size: 100
reg_weight: 0.01
latent_factor_model: BPR
loss_type: BPR